import { useState, useMemo } from 'react';
import { useProjectStore } from '../../stores/projectStore';
import { useGitHubStore } from '../../stores/githubStore';
import { generateTerraformProject, getAllFiles } from '../../generators';
import { createPullRequest } from '../../lib/github';
import type { ProjectConfig } from '../../types';

function generatePRBody(project: ProjectConfig): string {
  const enabledServices = Object.entries(project.services)
    .filter(([, v]) => v !== null)
    .map(([k]) => k.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()));

  const serviceList = enabledServices.map((s) => `- ${s}`).join('\n');

  return `## Terraform Infrastructure Configuration

Generated by [Terraform Builder](https://terraform-module-builder.vercel.app).

### Project Details

| Field | Value |
|-------|-------|
| Provider | ${project.provider.toUpperCase()} |
| Region | \`${project.region}\` |
| Environment | \`${project.environment}\` |

### Enabled Services

${serviceList || '- None'}

---

> Review \`terraform.tfvars\` to customise variable values before applying.
`;
}

interface PRModalProps {
  onClose: () => void;
}

export default function PRModal({ onClose }: PRModalProps) {
  const { project } = useProjectStore();
  const { token } = useGitHubStore();

  const generatedProject = useMemo(() => generateTerraformProject(project), [project]);
  const allFiles = useMemo(() => getAllFiles(generatedProject), [generatedProject]);

  const [owner, setOwner] = useState('');
  const [repo, setRepo] = useState('');
  const [directory, setDirectory] = useState('terraform');
  const [baseBranch, setBaseBranch] = useState('main');
  const [newBranch, setNewBranch] = useState(`feat/terraform-${project.name}`);
  const [prTitle, setPrTitle] = useState(`Add Terraform infrastructure for ${project.name}`);
  const [prBody, setPrBody] = useState(() => generatePRBody(project));

  const [isCreating, setIsCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [prUrl, setPrUrl] = useState<string | null>(null);

  const handleSubmit = async () => {
    if (!token || !owner || !repo || !newBranch || !prTitle) return;
    setIsCreating(true);
    setError(null);
    try {
      const result = await createPullRequest({
        token,
        owner,
        repo,
        directory,
        baseBranch,
        newBranch,
        title: prTitle,
        body: prBody,
        files: allFiles,
      });
      setPrUrl(result.url);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create pull request');
    } finally {
      setIsCreating(false);
    }
  };

  const inputClass =
    'w-full bg-white border border-gray-300 rounded-lg px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 transition-colors';
  const labelClass = 'block text-xs font-medium text-gray-600 mb-1';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
      <div className="bg-white rounded-2xl shadow-xl border border-gray-200 w-full max-w-lg mx-4 flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div className="flex items-center gap-3">
            <svg className="w-5 h-5 text-gray-500" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
            </svg>
            <h2 className="text-base font-semibold text-gray-900">Create GitHub Pull Request</h2>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Success state */}
        {prUrl ? (
          <div className="flex flex-col items-center gap-4 px-6 py-10 text-center">
            <div className="w-12 h-12 bg-green-500/20 rounded-full flex items-center justify-center">
              <svg className="w-6 h-6 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <div>
              <p className="text-gray-900 font-medium mb-1">Pull request created!</p>
              <p className="text-sm text-gray-500">Your Terraform configuration is ready for review.</p>
            </div>
            <a
              href={prUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg text-sm font-medium transition-colors"
            >
              View Pull Request
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
              </svg>
            </a>
            <button onClick={onClose} className="text-sm text-gray-500 hover:text-gray-700 transition-colors">
              Close
            </button>
          </div>
        ) : (
          <>
            {/* Form */}
            <div className="overflow-y-auto px-6 py-5 space-y-4 flex-1">
              {/* Repository */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className={labelClass}>Owner *</label>
                  <input
                    type="text"
                    value={owner}
                    onChange={(e) => setOwner(e.target.value)}
                    placeholder="username"
                    className={inputClass}
                  />
                </div>
                <div>
                  <label className={labelClass}>Repository *</label>
                  <input
                    type="text"
                    value={repo}
                    onChange={(e) => setRepo(e.target.value)}
                    placeholder="my-infra"
                    className={inputClass}
                  />
                </div>
              </div>

              {/* Directory */}
              <div>
                <label className={labelClass}>Directory in repo</label>
                <input
                  type="text"
                  value={directory}
                  onChange={(e) => setDirectory(e.target.value)}
                  placeholder="terraform"
                  className={inputClass}
                />
                <p className="text-xs text-gray-500 mt-1">
                  Files will be placed under <code className="text-gray-400">{directory || '/'}</code> in the repo.
                </p>
              </div>

              {/* Branches */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className={labelClass}>Base branch</label>
                  <input
                    type="text"
                    value={baseBranch}
                    onChange={(e) => setBaseBranch(e.target.value)}
                    placeholder="main"
                    className={inputClass}
                  />
                </div>
                <div>
                  <label className={labelClass}>New branch *</label>
                  <input
                    type="text"
                    value={newBranch}
                    onChange={(e) => setNewBranch(e.target.value)}
                    placeholder="feat/terraform-setup"
                    className={inputClass}
                  />
                </div>
              </div>

              {/* PR Title */}
              <div>
                <label className={labelClass}>PR Title *</label>
                <input
                  type="text"
                  value={prTitle}
                  onChange={(e) => setPrTitle(e.target.value)}
                  className={inputClass}
                />
              </div>

              {/* PR Body */}
              <div>
                <label className={labelClass}>PR Description</label>
                <textarea
                  value={prBody}
                  onChange={(e) => setPrBody(e.target.value)}
                  rows={6}
                  className={`${inputClass} resize-none font-mono text-xs`}
                />
              </div>

              {/* Files summary */}
              <div className="bg-gray-50 border border-gray-200 rounded-lg px-3 py-2">
                <p className="text-xs text-gray-500">
                  {allFiles.length} file{allFiles.length !== 1 ? 's' : ''} will be committed
                </p>
              </div>

              {/* Error */}
              {error && (
                <div className="bg-red-500/10 border border-red-500/30 rounded-lg px-3 py-2">
                  <p className="text-sm text-red-400">{error}</p>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-gray-200">
              <button
                onClick={onClose}
                className="px-4 py-2 text-sm text-gray-500 hover:text-gray-800 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleSubmit}
                disabled={isCreating || !owner || !repo || !newBranch || !prTitle}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 active:scale-95 ${
                  isCreating || !owner || !repo || !newBranch || !prTitle
                    ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                    : 'bg-orange-500 hover:bg-orange-600 text-white'
                }`}
              >
                {isCreating && (
                  <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                )}
                {isCreating ? 'Creating PR...' : 'Create Pull Request'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
