import { useState, useMemo } from 'react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { useProjectStore } from '../../stores/projectStore';
import { generateTerraformProject, getAllFiles } from '../../generators';

export default function Header() {
  const { project, resetProject } = useProjectStore();
  const [isDownloading, setIsDownloading] = useState(false);

  // Generate project to check if there's content
  const generatedProject = useMemo(() => {
    return generateTerraformProject(project);
  }, [project]);

  const hasContent = generatedProject.rootFiles.length > 0;

  const handleDownload = async () => {
    if (!hasContent) return;

    setIsDownloading(true);

    try {
      const zip = new JSZip();
      const allFiles = getAllFiles(generatedProject);

      // Add all files to the zip
      for (const file of allFiles) {
        zip.file(file.path, file.content);
      }

      // Add a README for the generated project
      const readme = `# ${project.name} - Terraform Infrastructure

This Terraform configuration was generated by Terraform Builder.

## Quick Start

1. **Initialize Terraform:**
   \`\`\`bash
   terraform init
   \`\`\`

2. **Review the plan:**
   \`\`\`bash
   terraform plan
   \`\`\`

3. **Apply the configuration:**
   \`\`\`bash
   terraform apply
   \`\`\`

## Project Structure

\`\`\`
${allFiles.map((f) => f.path).join('\n')}
\`\`\`

## Configuration

- **Project Name:** ${project.name}
- **AWS Region:** ${project.region}
- **Environment:** ${project.environment}

## Resources Created

${project.services.vpc ? '- VPC with Internet Gateway\n' : ''}${project.services.subnets ? `- ${project.services.subnets.public_subnet_cidrs.length} Public Subnet(s)\n` : ''}${project.services.subnets?.private_subnet_cidrs.length ? `- ${project.services.subnets.private_subnet_cidrs.length} Private Subnet(s)\n` : ''}${project.services.subnets?.create_nat_gateway ? '- NAT Gateway\n' : ''}${project.services.ec2 ? `- EC2 Instance (${project.services.ec2.instance_type})\n` : ''}${project.services.s3 ? '- S3 Bucket\n' : ''}${project.services.iam ? '- IAM Role and Instance Profile\n' : ''}

## Customization

Edit \`terraform.tfvars\` to customize the configuration values.

## Cleanup

To destroy all resources:
\`\`\`bash
terraform destroy
\`\`\`

---
Generated by [Terraform Builder](https://github.com/terraform-builder)
`;

      zip.file('README.md', readme);

      // Generate the zip file
      const content = await zip.generateAsync({ type: 'blob' });

      // Download the file
      saveAs(content, `${project.name}-terraform.zip`);
    } catch (error) {
      console.error('Error generating ZIP:', error);
      alert('Failed to generate ZIP file. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <header className="bg-gray-800 border-b border-gray-700 px-6 py-3 flex items-center justify-between">
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-orange-500 rounded-lg flex items-center justify-center">
            <svg
              className="w-5 h-5 text-white"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
              />
            </svg>
          </div>
          <div>
            <h1 className="text-lg font-bold text-white">Terraform Builder</h1>
            <p className="text-xs text-gray-400">
              Visual AWS Infrastructure Scaffolding
            </p>
          </div>
        </div>

        {hasContent && (
          <div className="hidden sm:flex items-center gap-2 px-3 py-1 bg-gray-700/50 rounded-lg">
            <span className="text-xs text-gray-400">Project:</span>
            <span className="text-sm font-medium text-white">{project.name}</span>
            <span className="text-gray-600">|</span>
            <span className="text-xs text-gray-400">{project.region}</span>
          </div>
        )}
      </div>

      <div className="flex items-center gap-3">
        <button
          onClick={resetProject}
          className="px-3 py-1.5 text-sm text-gray-300 hover:text-white hover:bg-gray-700 rounded-lg transition-colors"
        >
          Reset
        </button>

        <button
          onClick={handleDownload}
          disabled={!hasContent || isDownloading}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm transition-colors ${
            hasContent && !isDownloading
              ? 'bg-orange-500 hover:bg-orange-600 text-white'
              : 'bg-gray-700 text-gray-500 cursor-not-allowed'
          }`}
        >
          {isDownloading ? (
            <>
              <svg
                className="w-4 h-4 animate-spin"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                />
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                />
              </svg>
              Generating...
            </>
          ) : (
            <>
              <svg
                className="w-4 h-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
                />
              </svg>
              Download ZIP
            </>
          )}
        </button>
      </div>
    </header>
  );
}
