import { useState, useMemo } from 'react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { useProjectStore } from '../../stores/projectStore';
import { useGitHubStore } from '../../stores/githubStore';
import { generateTerraformProject, getAllFiles } from '../../generators';
import GitHubButton from './GitHubButton';

interface HeaderProps {
  onCreatePR: () => void;
}

export default function Header({ onCreatePR }: HeaderProps) {
  const { project, resetProject } = useProjectStore();
  const { token } = useGitHubStore();
  const [isDownloading, setIsDownloading] = useState(false);

  // Generate project to check if there's content
  const generatedProject = useMemo(() => {
    return generateTerraformProject(project);
  }, [project]);

  const hasContent = generatedProject.rootFiles.length > 0;

  const handleDownload = async () => {
    if (!hasContent) return;

    setIsDownloading(true);

    try {
      const zip = new JSZip();
      const allFiles = getAllFiles(generatedProject);

      // Add all files to the zip
      for (const file of allFiles) {
        zip.file(file.path, file.content);
      }

      // Add a README for the generated project
      const readme = `# ${project.name} - Terraform Infrastructure

This Terraform configuration was generated by Terraform Builder.

## Quick Start

1. **Initialize Terraform:**
   \`\`\`bash
   terraform init
   \`\`\`

2. **Review the plan:**
   \`\`\`bash
   terraform plan
   \`\`\`

3. **Apply the configuration:**
   \`\`\`bash
   terraform apply
   \`\`\`

## Project Structure

\`\`\`
${allFiles.map((f) => f.path).join('\n')}
\`\`\`

## Configuration

- **Project Name:** ${project.name}
- **AWS Region:** ${project.region}
- **Environment:** ${project.environment}

## Resources Created

${project.services.vpc ? '- VPC with Internet Gateway\n' : ''}${project.services.subnets ? `- ${project.services.subnets.public_subnet_cidrs.length} Public Subnet(s)\n` : ''}${project.services.subnets?.private_subnet_cidrs.length ? `- ${project.services.subnets.private_subnet_cidrs.length} Private Subnet(s)\n` : ''}${project.services.subnets?.create_nat_gateway ? '- NAT Gateway\n' : ''}${project.services.ec2 ? `- EC2 Instance (${project.services.ec2.instance_type})\n` : ''}${project.services.s3 ? '- S3 Bucket\n' : ''}${project.services.iam ? '- IAM Role and Instance Profile\n' : ''}

## Customization

Edit \`terraform.tfvars\` to customize the configuration values.

## Cleanup

To destroy all resources:
\`\`\`bash
terraform destroy
\`\`\`

---
Generated by [Terraform Builder](https://github.com/terraform-builder)
`;

      zip.file('README.md', readme);

      // Generate the zip file
      const content = await zip.generateAsync({ type: 'blob' });

      // Download the file
      saveAs(content, `${project.name}-terraform.zip`);
    } catch (error) {
      console.error('Error generating ZIP:', error);
      alert('Failed to generate ZIP file. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <header className="bg-gray-800/95 px-6 py-3 flex items-center justify-between shadow-lg shadow-black/20">
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 bg-orange-500 rounded-xl flex items-center justify-center shadow-md shadow-orange-500/30">
            <svg
              className="w-5 h-5 text-white"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
              />
            </svg>
          </div>
          <div>
            <h1 className="text-lg font-bold text-white">Terraform Builder</h1>
            <p className="text-xs text-gray-400">
              Visual AWS Infrastructure Scaffolding
            </p>
          </div>
        </div>

        {hasContent && (
          <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 bg-gray-700/50 rounded-xl shadow-inner">
            <span className="text-xs text-gray-400">Project:</span>
            <span className="text-sm font-medium text-white">{project.name}</span>
            <span className="text-gray-600">|</span>
            <span className="text-xs text-gray-400">{project.region}</span>
          </div>
        )}
      </div>

      <div className="flex items-center gap-3">
        <GitHubButton />

        <button
          onClick={resetProject}
          className="btn-soft px-3 py-1.5 text-sm text-gray-300 hover:text-white hover:bg-gray-700/80 rounded-lg transition-all duration-200 active:scale-95"
        >
          Reset
        </button>

        {token && hasContent && (
          <button
            onClick={onCreatePR}
            className="btn-soft flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm bg-gray-700 hover:bg-gray-600 text-gray-200 hover:text-white transition-all duration-200 active:scale-95"
          >
            <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
            </svg>
            Create PR
          </button>
        )}

        <button
          onClick={handleDownload}
          disabled={!hasContent || isDownloading}
          className={`btn-soft flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm transition-all duration-200 active:scale-95 ${
            hasContent && !isDownloading
              ? 'bg-orange-500 hover:bg-orange-600 hover:shadow-lg hover:shadow-orange-500/30 text-white'
              : 'bg-gray-700 text-gray-500 cursor-not-allowed scale-100'
          }`}
        >
          {isDownloading ? (
            <>
              <svg
                className="w-4 h-4 animate-spin"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                />
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                />
              </svg>
              Generating...
            </>
          ) : (
            <>
              <svg
                className="w-4 h-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
                />
              </svg>
              Download ZIP
            </>
          )}
        </button>
      </div>
    </header>
  );
}
