import { useState, useMemo } from 'react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { useProjectStore } from '../../stores/projectStore';
import { useGitHubStore } from '../../stores/githubStore';
import { generateTerraformProject, getAllFiles } from '../../generators';
import GitHubButton from './GitHubButton';

interface HeaderProps {
  onCreatePR: () => void;
}

export default function Header({ onCreatePR }: HeaderProps) {
  const { project, resetProject } = useProjectStore();
  const { token } = useGitHubStore();
  const [isDownloading, setIsDownloading] = useState(false);

  const generatedProject = useMemo(() => generateTerraformProject(project), [project]);
  const hasContent = generatedProject.rootFiles.length > 0;

  const handleDownload = async () => {
    if (!hasContent) return;
    setIsDownloading(true);
    try {
      const zip = new JSZip();
      const allFiles = getAllFiles(generatedProject);
      for (const file of allFiles) {
        zip.file(file.path, file.content);
      }

      const readme = `# ${project.name} - Terraform Infrastructure

This Terraform configuration was generated by Terraform Builder.

## Quick Start

1. **Initialize Terraform:**
   \`\`\`bash
   terraform init
   \`\`\`

2. **Review the plan:**
   \`\`\`bash
   terraform plan
   \`\`\`

3. **Apply the configuration:**
   \`\`\`bash
   terraform apply
   \`\`\`

## Project Structure

\`\`\`
${allFiles.map((f) => f.path).join('\n')}
\`\`\`

## Configuration

- **Project Name:** ${project.name}
- **Region:** ${project.region}
- **Environment:** ${project.environment}
`;
      zip.file('README.md', readme);
      const content = await zip.generateAsync({ type: 'blob' });
      saveAs(content, `${project.name}-terraform.zip`);
    } catch (error) {
      console.error('Error generating ZIP:', error);
      alert('Failed to generate ZIP file. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <header className="bg-white border-b border-gray-200 px-5 py-3 flex items-center justify-between flex-shrink-0">
      {/* Left: Logo + project badge */}
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 bg-blue-600 rounded-xl flex items-center justify-center flex-shrink-0">
            <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
            </svg>
          </div>
          <div>
            <h1 className="text-sm font-bold text-gray-900 leading-tight">Terraform Builder</h1>
            <p className="text-xs text-gray-400 leading-tight">Visual Infrastructure Scaffolding</p>
          </div>
        </div>

        {hasContent && (
          <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 bg-gray-100 rounded-lg">
            <span className="text-xs text-gray-500">Project:</span>
            <span className="text-xs font-semibold text-gray-800">{project.name}</span>
            <span className="text-gray-300">|</span>
            <span className="text-xs text-gray-500">{project.region}</span>
          </div>
        )}
      </div>

      {/* Right: actions */}
      <div className="flex items-center gap-2">
        <GitHubButton />

        <button
          onClick={resetProject}
          className="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-all duration-150"
        >
          Reset
        </button>

        {token && hasContent && (
          <button
            onClick={onCreatePR}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium border border-gray-300 text-gray-700 hover:bg-gray-50 transition-all duration-150 active:scale-95"
          >
            <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
            </svg>
            Create PR
          </button>
        )}

        <button
          onClick={handleDownload}
          disabled={!hasContent || isDownloading}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm transition-all duration-150 active:scale-95 ${
            hasContent && !isDownloading
              ? 'bg-blue-600 hover:bg-blue-700 text-white shadow-sm'
              : 'bg-gray-100 text-gray-400 cursor-not-allowed'
          }`}
        >
          {isDownloading ? (
            <>
              <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Generating...
            </>
          ) : (
            <>
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Download ZIP
            </>
          )}
        </button>
      </div>
    </header>
  );
}
