import type { ProjectConfig } from '../../types';

// =============================================================================
// Azure Root Module Generator
// =============================================================================

export function generateAzureRootMain(project: ProjectConfig): string {
  const s = project.services;
  const sections: string[] = [];

  // Terraform configuration block
  sections.push(`# =============================================================================
# ${project.name} - Azure Infrastructure
# Generated by Terraform Builder
# =============================================================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }

  # Uncomment and configure for remote state
  # backend "azurerm" {
  #   resource_group_name  = "tfstate"
  #   storage_account_name = "tfstate"
  #   container_name       = "tfstate"
  #   key                  = "${project.name}.tfstate"
  # }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

# =============================================================================
# Resource Group
# =============================================================================

resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.location

  tags = local.common_tags
}

# Key Vault for secrets
resource "azurerm_key_vault" "main" {
  name                       = "\${var.project_name}-kv"
  location                   = azurerm_resource_group.main.location
  resource_group_name        = azurerm_resource_group.main.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  soft_delete_retention_days = 7
  purge_protection_enabled   = false

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    secret_permissions = [
      "Get", "List", "Set", "Delete", "Purge"
    ]
  }

  tags = local.common_tags
}

data "azurerm_client_config" "current" {}

# =============================================================================
# Local Values
# =============================================================================

locals {
  common_tags = merge(var.tags, {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "Terraform"
  })
}`);

  // Identity module (often needed first)
  if (s.iam) {
    sections.push(`
# =============================================================================
# Identity Module
# =============================================================================

module "identity" {
  source = "./modules/identity"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  resource_group_id   = azurerm_resource_group.main.id
  ${s.s3 ? 'storage_account_id   = module.storage.storage_account_id' : 'storage_account_id   = ""'}
  key_vault_id        = azurerm_key_vault.main.id

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main]
}`);
  }

  // Networking module
  if (s.vpc || s.subnets || s.security_groups) {
    sections.push(`
# =============================================================================
# Networking Module
# =============================================================================

module "networking" {
  source = "./modules/networking"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main]
}`);
  }

  // Compute module
  if (s.ec2) {
    sections.push(`
# =============================================================================
# Compute Module
# =============================================================================

module "compute" {
  source = "./modules/compute"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  subnet_id           = module.networking.public_subnet_ids[0]
  nsg_id              = try(module.networking.nsg_ids["web"], "")
  ssh_public_key      = var.ssh_public_key
  ${s.iam ? 'managed_identity_id = module.identity.identity_id' : ''}

  tags = local.common_tags

  depends_on = [module.networking${s.iam ? ', module.identity' : ''}]
}`);
  }

  // Storage module
  if (s.s3) {
    sections.push(`
# =============================================================================
# Storage Module
# =============================================================================

module "storage" {
  source = "./modules/storage"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main]
}`);
  }

  // Database module
  if (s.rds) {
    sections.push(`
# =============================================================================
# Database Module
# =============================================================================

module "database" {
  source = "./modules/database"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  key_vault_id        = azurerm_key_vault.main.id
  ${s.vpc ? 'subnet_id           = module.networking.private_subnet_ids[0]' : ''}

  tags = local.common_tags

  depends_on = [${s.vpc ? 'module.networking, ' : ''}azurerm_key_vault.main]
}`);
  }

  // Serverless module
  if (s.lambda) {
    sections.push(`
# =============================================================================
# Serverless Module (Azure Functions)
# =============================================================================

module "serverless" {
  source = "./modules/serverless"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  ${s.iam ? 'managed_identity_id = module.identity.identity_id' : ''}
  ${s.vpc ? 'subnet_id           = module.networking.private_subnet_ids[0]' : ''}

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main${s.iam ? ', module.identity' : ''}]
}`);
  }

  // API module
  if (s.api_gateway) {
    sections.push(`
# =============================================================================
# API Module (API Management)
# =============================================================================

module "api" {
  source = "./modules/api"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  publisher_email     = var.api_publisher_email

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main]
}`);
  }

  // Messaging module
  if (s.sqs || s.sns) {
    sections.push(`
# =============================================================================
# Messaging Module (Service Bus)
# =============================================================================

module "messaging" {
  source = "./modules/messaging"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main]
}`);
  }

  // Events module
  if (s.eventbridge) {
    sections.push(`
# =============================================================================
# Events Module (Event Grid)
# =============================================================================

module "events" {
  source = "./modules/events"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  resource_group_id   = azurerm_resource_group.main.id

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main]
}`);
  }

  // Monitoring module
  if (s.cloudwatch) {
    sections.push(`
# =============================================================================
# Monitoring Module (Azure Monitor)
# =============================================================================

module "monitoring" {
  source = "./modules/monitoring"

  project_name        = var.project_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main]
}`);
  }

  // CDN module
  if (s.cloudfront) {
    sections.push(`
# =============================================================================
# CDN Module (Azure CDN)
# =============================================================================

module "cdn" {
  source = "./modules/cdn"

  project_name        = var.project_name
  resource_group_name = azurerm_resource_group.main.name
  origin_hostname     = ${s.s3 ? 'module.storage.primary_web_endpoint' : 'var.cdn_origin_hostname'}

  tags = local.common_tags

  depends_on = [${s.s3 ? 'module.storage' : 'azurerm_resource_group.main'}]
}`);
  }

  // Email module
  if (s.ses) {
    sections.push(`
# =============================================================================
# Email Module (Communication Services)
# =============================================================================

module "email" {
  source = "./modules/email"

  project_name        = var.project_name
  resource_group_name = azurerm_resource_group.main.name

  tags = local.common_tags

  depends_on = [azurerm_resource_group.main]
}`);
  }

  return sections.join('\n');
}

// =============================================================================
// Variables
// =============================================================================

export function generateAzureRootVariables(project: ProjectConfig): string {
  const s = project.services;
  const vars: string[] = [];

  vars.push(`# =============================================================================
# Core Variables
# =============================================================================

variable "project_name" {
  description = "Name of the project"
  type        = string
  default     = "${project.name}"
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "${project.region}"
}

variable "resource_group_name" {
  description = "Name of the resource group"
  type        = string
  default     = "${project.resourceGroup || `rg-${project.name}`}"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "${project.environment}"
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default     = ${JSON.stringify(project.tags, null, 2).replace(/\n/g, '\n  ')}
}`);

  if (s.ec2) {
    vars.push(`
# =============================================================================
# Compute Variables
# =============================================================================

variable "ssh_public_key" {
  description = "SSH public key for VM access"
  type        = string
}`);
  }

  if (s.api_gateway) {
    vars.push(`
# =============================================================================
# API Variables
# =============================================================================

variable "api_publisher_email" {
  description = "Publisher email for API Management"
  type        = string
}`);
  }

  if (s.cloudfront && !s.s3) {
    vars.push(`
# =============================================================================
# CDN Variables
# =============================================================================

variable "cdn_origin_hostname" {
  description = "Origin hostname for CDN"
  type        = string
}`);
  }

  return vars.join('\n');
}

// =============================================================================
// Outputs
// =============================================================================

export function generateAzureRootOutputs(project: ProjectConfig): string {
  const s = project.services;
  const outputs: string[] = [];

  outputs.push(`# =============================================================================
# Core Outputs
# =============================================================================

output "resource_group_name" {
  description = "Name of the resource group"
  value       = azurerm_resource_group.main.name
}

output "resource_group_id" {
  description = "ID of the resource group"
  value       = azurerm_resource_group.main.id
}

output "key_vault_id" {
  description = "ID of the Key Vault"
  value       = azurerm_key_vault.main.id
}

output "key_vault_uri" {
  description = "URI of the Key Vault"
  value       = azurerm_key_vault.main.vault_uri
}`);

  if (s.vpc) {
    outputs.push(`
# =============================================================================
# Networking Outputs
# =============================================================================

output "vnet_id" {
  description = "ID of the virtual network"
  value       = module.networking.vnet_id
}

output "vnet_name" {
  description = "Name of the virtual network"
  value       = module.networking.vnet_name
}`);
  }

  if (s.ec2) {
    outputs.push(`
# =============================================================================
# Compute Outputs
# =============================================================================

output "vm_public_ip" {
  description = "Public IP of the virtual machine"
  value       = module.compute.public_ip
}`);
  }

  if (s.s3) {
    outputs.push(`
# =============================================================================
# Storage Outputs
# =============================================================================

output "storage_account_name" {
  description = "Name of the storage account"
  value       = module.storage.storage_account_name
}

output "primary_blob_endpoint" {
  description = "Primary blob endpoint"
  value       = module.storage.primary_blob_endpoint
}`);
  }

  if (s.rds) {
    outputs.push(`
# =============================================================================
# Database Outputs
# =============================================================================

output "database_server_fqdn" {
  description = "FQDN of the database server"
  value       = module.database.server_fqdn
}`);
  }

  if (s.lambda) {
    outputs.push(`
# =============================================================================
# Serverless Outputs
# =============================================================================

output "function_hostnames" {
  description = "Hostnames of the function apps"
  value       = module.serverless
}`);
  }

  if (s.cloudfront) {
    outputs.push(`
# =============================================================================
# CDN Outputs
# =============================================================================

output "cdn_endpoint_url" {
  description = "URL of the CDN endpoint"
  value       = module.cdn.cdn_endpoint_url
}`);
  }

  return outputs.join('\n');
}
